<SavedScreen>:
    name: 'saved'
    MDScreen:

        MDBoxLayout:
            orientation: 'vertical'
            size_hint_y: 1

            MDTextField:
                id: search_field
                mode: "rectangle"
                icon_left: "magnify"
                size_hint_x: 0.9
                size_hint_y: None
                height: "50dp"
                pos_hint: {"center_x": 0.5}
                md_bg_color: 0.95, 0.92, 1, 1
                radius: [25,]

            MDLabel:
                text: "Saved Workouts"
                font_style: "H5"
                size_hint_y: None
                height: dp(40)
                padding: dp(10)

            ScrollView:
                do_scroll_x: False
                do_scroll_y: True

                RecycleView:
                    id: saved_workout_list
                    viewclass: "WorkoutItem"

                    RecycleBoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: dp(15)
                        padding: dp(10)

        MDBottomNavigation:
            id: bottom_nav
            height: "60dp"
            panel_color: "#eeeeee"
            pos_hint: {"bottom": 1}

            MDBottomNavigationItem:
                name: "home"
                text: "Home"
                icon: "home"
                on_tab_press: app.root.current = "home"

            MDBottomNavigationItem:
                name: "saved"
                text: "Saved"
                icon: "bookmark"
                on_tab_press: app.root.current = "saved"

            MDBottomNavigationItem:
                name: "user"
                text: "User"
                icon: "account"
                on_tab_press: app.root.current = "user"

<WorkoutItem>:
    size_hint_y: None
    height: dp(120)
    orientation: "vertical"
    on_release: app.root.current = root.target_screen

    MDCard:
        radius: dp(10)
        md_bg_color: 0.9, 0.9, 1, 1
        size_hint_x: 0.9
        pos_hint: {"center_x": 0.5}
        elevation: 5

        BoxLayout:
            orientation: "horizontal"

            Image:
                source: root.image_source
                size_hint_x: 0.3
                allow_stretch: True

            MDLabel:
                text: root.title
                halign: "center"
