@echo off
echo [🔧] Creating virtual environment...
python -m venv venv

echo [📦] Activating virtual environment...
call venv\Scripts\activate

echo [⬇️] Installing dependencies...
pip install -r requirements.txt

echo [🚀] You can now start the FlexFit App...

pause